### ISSUE TITLE
Allow the setting of S3ClientOptions on AmazonS3Client object

### ISSUE THREAD

**Issue by Swedeski** [elastic/elasticsearch-cloud-aws#124]
I am trying to use my own S3 repository to store snapshots and have an SSL enabled endpoint that does not support virtual hosting.  I need to use path style access to access the endpoint.

Ultimately I'd like to define a setting in the elasticsearch.yml file that indicates that it should use the "path style access" option.  Perhaps something like: **cloud.aws.s3clientoption.path_style_access: true**

Setting the property would result in the *S3ClientOption.setPathStyleAccess()* method being called with true and then those client options being set on the AmazonS3Client object.

I pulled the code, made a modification locally to the *org.elasticsearch.cloud.aws.InternalAwsS3Service.getClient(String, String, String)* method to set the path style access to true to make sure this would solve my problems.

Here is the simple hack I implemented in the InternalAwsS3Service class to test it out:
![image](https://cloud.githubusercontent.com/assets/8794262/4649741/8297f14a-548d-11e4-8112-072faa6d6954.png)

After I made the change the plugin worked as expected and I was able to store the snapshots in my own S3 repository and restore from that repository as well.

Any help in getting this functionality into the plugin would be greatly appreciated.

**Comment by dadoonet** [comment]
I added a PR for this. See #159.

**Comment by dadoonet** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/15114
