### ISSUE TITLE
Issue with region cn-north-1 s3 endpoint

### ISSUE THREAD

**Issue by zhaojin0** [elastic/elasticsearch-cloud-aws#166]
Region cn-north-1
S3 endpoint is 's3.cn-north-1.amazonaws.com.cn', not 's3.cn-north-1.amazonaws.com'.
Thanks.

**Comment by dadoonet** [comment]
This is fixed in 2.4.2 with #156 and this commit 4c02a017b43539d26964b639a71bf589cba1f72c

**Comment by zhaojin0** [comment]
thanks!
