### ISSUE TITLE
Separate proxy traffic for ec2 and s3.

### ISSUE THREAD

**Issue by paul-e-cooley** [elastic/elasticsearch-cloud-aws#177]
We have a specific need to set a proxy at the s3 level separate from ec2. If a proxy goes down for whatever reason, we do not want ec2 traffic blocked since s3 traffic is used only for backups. Currently the plugin supports an all or nothing approach. I've already made a fork of the project and tested our changes.

I'm certain we are not the only ones that need the feature.

**Comment by dadoonet** [comment]
Going to send a PR?

**Comment by paul-e-cooley** [comment]
PR sent.
