### ISSUE TITLE
EC2 Autodiscovery not working with OpenJDK 8

### ISSUE THREAD

**Issue by nikolay** [elastic/elasticsearch-cloud-aws#181]
I keep getting the following error: `Exception while retrieving instance list from AWS API: Unable to execute HTTP request: peer not authenticated`

I used the recommended by you IAM role and things worked fine with Elasticsearch v1.4.2 and v2.4.1 of the plugin, but things no longer work for me. I tried overriding IAM and using omnipotent AWS keys - I still get the error regardlessly.

**Comment by nikolay** [comment]
I downgraded to v1.4.2 and it's not working either.

**Comment by nikolay** [comment]
@dadoonet Any comment? I can provide more details if there's any interest to help solve this.

**Comment by dadoonet** [comment]
@nikolay Sorry for the delay. Wondering which JAVA vendor you are using? Any chance you are using OpenJDK instead of Oracle?

**Comment by nikolay** [comment]
@dadoonet OpenJDK 8.

**Comment by dadoonet** [comment]
Any chance you could test with Oracle JDK?

**Comment by nikolay** [comment]
Our preferences are OpenJDK > [Zulu](http://www.azulsystems.com/products/zulu) > Oracle JDK, with Oracle's being least desired due to the fact that it's purposely not well-suited for automatic installs. Of course, we can use WebUpd8's PPA, but that's hacky. Let me try though.

**Comment by dadoonet** [comment]
Yes please. I just like to confirm it is a AWS API issue with OpenJDK as I have read on some websites.
Once confirmed, we can try to see if there is any workaround or if we should mention in docs that the plugin is not compatible with Java version X vendor Y.

**Comment by nikolay** [comment]
@dadoonet It was an issue with OpenJDK 8, which doesn't seem to be supported by (at least) v2.4.1. It would be nice if you can address the issue, but post a compatibility note here so that other people don't waste time like I did. Thanks in advance!

**Comment by dadoonet** [comment]
I also remember that this could happen when time is not synch'ed with NTP.
Could you check that as well please? 

If your machine had incorrect time, could you fix it and try again with open JDK ?

**Comment by nikolay** [comment]
All my machines are in sync and were launched at the same time EC2 instances. My user data already has NTP enabled and updated. Not sure if it's relevant, but this is on Ubuntu 14.10 (and thus OpenJDK 8, which is not available in the latest LTS release).

**Comment by dadoonet** [comment]
@nikolay We released recently new versions of the cloud-aws plugin. Any chance you can test 2.7.1 with es 1.7 on OpenJDK 8?

**Comment by vazhnov** [comment]
I got this error in Ubuntu 15.04, Elasticsearch 1.5.2, AWS Cloud Plugin 2.5.0, OpenJDK 8.
Fixed by:
```shell
sudo update-ca-certificates -f
```

**Comment by dadoonet** [comment]
Closing. No further news on this so I suppose everything is fine now with the recent versions.
