### ISSUE TITLE
Remove `cloud.account` and `cloud.key` settings

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-aws#183]
`cloud.account` and `cloud.key` settings are not documented as we use `cloud.aws.access_key` and `cloud.aws.secret_key` settings instead.

We can deprecated those settings in `es-1.4` branch and remove them in `master`.

**Comment by dadoonet** [comment]
@imotov WDYT?

**Comment by imotov** [comment]
Personally I like `cloud.account` and `cloud.key` more (mostly because they are shorter). But I can see how this can cause some confusion. Not sure.

**Comment by dadoonet** [comment]
Yeah. If we want to mix within a node azure settings and aws settings (let say backup in two places), I think it's better to prefix setting name.

**Comment by kimchy** [comment]
we do support both, right? I mean, sure, we can simplify and not provide too many options to configure things and be more explicit around the actual aws settings

**Comment by dadoonet** [comment]
we do support both today. But the simplest form `cloud.account` is not documented AFAIK.

**Comment by nikolay** [comment]
@imotov With AWS, "account" and "access key" are two different things, so, `cloud.account` will be misleading.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#12809
