### ISSUE TITLE
Debug level log activity about missing `site` directory

### ISSUE THREAD

**Issue by eugenp** [elastic/elasticsearch-cloud-aws#192]
I am seeing the following debug level message in my logs (multiple times): 
```
[DEBUG][plugins                  ] [Goldeneye] [/opt/uptake/elasticsearch-1.4.4/plugins/cloud-aws/_site] directory does not exist.
```
I am using the latest (2.4.1) version of the plugin and I got no error/warning during installation. 
Am I missing something? Or is this a known issue? Thanks.

**Comment by dadoonet** [comment]
That's perfectly fine. It's a DEBUG message from the plugin manager.

**Comment by eugenp** [comment]
I fully agree that this is not a major problem. However, even being a small issue - would it make sense to fix it? 
The reason I say that is simply that, when you have your logs on DEBUG - this will continue to write that message into the log, continuously, every few seconds. And of course that makes the actual issue you might be trying to debug hard to spot between all that unnecessary logging. 
Again, not a major issue - I'm just thinking it might be a quick fix. Cheers, 
Eugen.

**Comment by dadoonet** [comment]
Never saw that It happens so often. IIRC that might happen if you call a _cat API.
Will check this.
If it's the case, we might change level to TRACE.

Whatever, it's an Elasticsearch core concerns and not related to this plugin.
