### ISSUE TITLE
Compatibility with Elasticsearch v1.5

### ISSUE THREAD

**Issue by nikolay** [elastic/elasticsearch-cloud-aws#195]
As v2.4.2 is pretty dated already, and I don't see a v2.5 milestone (but it's what is supposedly compatible with ES v1.5), will a version be available so that we can upgrade ES anytime soon?

**Comment by mewwts** [comment]
Waiting for this as well :+1:

**Comment by shreyu86** [comment]
+1 this is a blocker in upgrading to ES 1.5.0

**Comment by kimchy** [comment]
hey, we will release a new version first thing tomorrow morning, stay tuned and apologies for the delay

**Comment by shreyu86** [comment]
thanks for the update @kimchy :)

**Comment by mewwts** [comment]
Thanks a bunch @kimchy @dadoonet! :+1:

**Comment by dadoonet** [comment]
Heya


We just released version 2.5.0 for elasticsearch 1.5.0.

Let us know if you have any issue with it by opening new issues in this repo.
Thanks!

**Comment by noamgal** [comment]
@dadoonet looking good, thanks
