### ISSUE TITLE
autodiscovery not working in multi-node single-host installation

### ISSUE THREAD

**Issue by uwebartels** [elastic/elasticsearch-cloud-aws#197]
Hiho,

I probably have a quite special installation. I'm running es-1.4.4 cluster on a single machine with
- one node: node0 with the role master only for loadbalancing and split-brain-problem
- two nodes: node1 and node2 with the roles master+data each as the workhorses
When I start node1 first, then all the other nodes I have a complete cluster running with node1 bound to port 9300. The others bound to port 9301 and 9302.

now I try to code a rolling restart.

When I restart node1 first then node1 starts up successfully but doesn't find the other nodes on the same machine bound to port 9301 and 9302.

Is there a way to get this working?
I know this is a special kind of installation that doesn't makes sense on aws, but aws is my testbed for other installations using zen discovery.

Thanks,
Uwe

**Comment by jerry4** [comment]
I think your issue is similar to #99 (closed without fix)  and elastic/elasticsearch#7090 (still open, but there is a pull request associated). I ended up forking and adding that fix into my own local branch.

Hope this helps (and that the number of ports to scan becomes configurable at some point).

Jerry

**Comment by uwebartels** [comment]
Hi, Jerry,

good to know that it doesn't work right now.
yesterday coded and tested that in my production environment. not nice, 
but our environment does not have need that high availability yet.

Best...
Uwe

Am 28/4/2015 um 23:15 schrieb jerry4:

**Comment by dadoonet** [comment]
This won't be fix in this plugin but in elasticsearch core itself.
See https://github.com/elastic/elasticsearch/pull/8833.

Closing.
