### ISSUE TITLE
AbstractS3SnapshotRestoreTest.testRepositoryWithCustomEndpointProtocol() fails often

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch-cloud-aws#211]
I'm marking this one `@AwaitsFix` to get builds stable. But this failed for me locally and seems to fail in jenkins (e.g. http://build-eu-00.elastic.co/job/es_aws/1195/)

**Comment by rmuir** [comment]
Trying to run locally and looking at jenkins logs, i see it with quite a few methods in this test.

**Comment by tlrx** [comment]
Closing, too old.
