### ISSUE TITLE
Exceeded rate limit on EC2 API calls

### ISSUE THREAD

**Issue by chaudum** [elastic/elasticsearch-cloud-aws#229]
Hi,

We've built in the EC2 discovery mechanism into Crate and experienced exceeding the rate limit / quota of EC2 API requests when starting a few nodes simultaneously. I just wanted to ask if you ever had such an issue?

```
[2015-08-03 15:38:58,792][INFO ][discovery.ec2            ] [ip-10-126-3-11] Exception while retrieving instance list from AWS API: Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: 4018ede3-411f-49eb-bc00-1b8d11a8837f) 
```

We now do cache the node list from the EC2 request if it is not empty. https://github.com/crate/elasticsearch-cloud-aws/commit/3f5383ca5a364343d14435e43db115ba6452868b
I could do a PR with these changes if you want.

Best,
Christian

**Comment by roivanov** [comment]
+1

**Comment by jeremysanecki** [comment]
+1

**Comment by chaudum** [comment]
made a PR https://github.com/elastic/elasticsearch-cloud-aws/pull/231

**Comment by aedades** [comment]
+1

**Comment by rtkmhart** [comment]
We ran into this as well. The plugin should have some sort of back-off strategy.

**Comment by dadoonet** [comment]
This will be closed when https://github.com/elastic/elasticsearch/pull/14155 will be merged.
Closing this one in favor of the PR and https://github.com/elastic/elasticsearch/issues/14099
