### ISSUE TITLE
No Elasticsearch 2.0 support

### ISSUE THREAD

**Issue by zcox** [elastic/elasticsearch-cloud-aws#250]
Unable to install discovery-ec2 and repository-s3 plugins in Elasticsearch 2.0:

`bin/plugin install --verbose discovery-ec2` results in:

```
-> Installing discovery-ec2...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/discovery-ec2/2.0.0/discovery-ec2-2.0.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/discovery-ec2/2.0.0/discovery-ec2-2.0.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/discovery-ec2/2.0.0/discovery-ec2-2.0.0.zip];
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```

`bin/plugin install --verbose repository-s3` results in:

```
-> Installing repository-s3...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip];
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```

**Comment by xuzha** [comment]
The split is in 3.0, there are no discovery-ec2 and repository-s3 plugin.  Try to use `cloud-aws`. 

If you try this with 3.0, you could try to download and build from the Elasticsearch source, and install them via files : `/bin/plugin install file:[path-to-repository-s3-3.0.0-SNAPSHOT.zip]`

Close this.

**Comment by zcox** [comment]
@xuzha `bin/plugin install cloud-aws` worked in Elasticsearch 2.0, thanks!

**Comment by dadoonet** [comment]
Out of curiosity, why did you think at the beginning that repository-s3 was a correct plugin name?
I mean: where did you get this information?

**Comment by davidski** [comment]
@dadoonet - As a follower of the project, I've been a bit unclear myself from the readme (https://github.com/elastic/elasticsearch-cloud-aws) and from many of the recent comments here on this plugin's repo about the two subdivided plugins under the elastic branch. Is there a FAQ somewhere that details how the split of `cloud-aws` is going to take place and when? Thanks!

**Comment by dadoonet** [comment]
Of course ! The first line of the README!

I need to fix that because it's confusing.

Thanks.

The split has been done in master branch (3.0.0-SNAPSHOT). https://www.elastic.co/guide/en/elasticsearch/reference/master/_plugins.html#_cloud_aws_plugin

**Comment by dadoonet** [comment]
So I just updated the README.

**Comment by davidski** [comment]
Thanks for doing that! Now I know not to worry about the plugin architecture changing radically in the immediate future. :smile:

**Comment by zcox** [comment]
@dadoonet it was indeed the first line of the readme that led me to believe instead of cloud-aws, I needed to install discovery-ec2 and repository-s3 plugins. Thank you for fixing the readme. :+1:

**Comment by floretan** [comment]
The wrong reference to the repository-s3 plugin is still mentioned here too: https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-s3.html

**Comment by dadoonet** [comment]
@floretan Why do you think it's wrong? In master branch, it looks correct to me.

**Comment by floretan** [comment]
@dadoonet Sorry, it is indeed correct for the master branch. The different plugin names are quite confusing though, it would be helpful to make sure that every version of these instructions specifies what version of elasticsearch they apply to, most people won't reach them through the readme file.

**Comment by dadoonet** [comment]
Is there something we should change at the beginning of the README file?

<img width="711" alt="elastic-elasticsearch-cloud-aws google chrome aujourd hui at 14 43 21" src="https://cloud.githubusercontent.com/assets/274222/12265021/da4128c2-b93a-11e5-8cc4-4a2248546c0d.png">
