### ISSUE TITLE
Installing plugin in ES2.0 fails

### ISSUE THREAD

**Issue by phutchins** [elastic/elasticsearch-cloud-aws#251]
Looks like we're missing a required file to install in 2.0...

bin/plugin install https://github.com/elastic/elasticsearch-cloud-aws/archive/v2.7.1.zip
-> Installing from https://github.com/elastic/elasticsearch-cloud-aws/archive/v2.7.1.zip...
Trying https://github.com/elastic/elasticsearch-cloud-aws/archive/v2.7.1.zip ...
Downloading .............................................................DONE
Verifying https://github.com/elastic/elasticsearch-cloud-aws/archive/v2.7.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by dadoonet** [comment]
Have a look at the very first lines in the README.

**Comment by phutchins** [comment]
Saw those just after I posted this. Went to close this and you beat me to it. :)
