### ISSUE TITLE
plugin-descriptor.properties missing error

### ISSUE THREAD

**Issue by leunamnauj** [elastic/elasticsearch-cloud-aws#254]
Hello,
I got the following error during plugin installation:

/usr/share/elasticsearch# bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.7.1
-> Installing elasticsearch/elasticsearch-cloud-aws/2.7.1...
Trying https://download.elastic.co/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.7.1.zip ...
Downloading ........................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.7.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

Plugin is going to be updated to fix this?

Thanks in advance

**Comment by dadoonet** [comment]
May be you missed the **IMPORTANT** part of the README (the very first lines)?

With ES 2.0 don't use this repo anymore.

**Comment by leunamnauj** [comment]
You are so right, I've missed the first part but now I have the following problem:

bin/plugin install repository-s3 --verbose
-> Installing repository-s3...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.0.0/repository-s3-2.0.0.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by dadoonet** [comment]
Ok. The README says:

> **IMPORTANT**: this project now moved to elasticsearch repository (from elasticsearch 2.0.0): 
> 
> * [cloud-aws](https://github.com/elastic/elasticsearch/tree/2.0/plugins/cloud-aws) ([documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws.html))

Unless you are testing your own elasticsearch version on master branch, please follow the documentation link: https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws.html

**Comment by leunamnauj** [comment]
Hello David,
Has worked perfectly, my brain is just not working today.

Thank you very much for your support and patience!
