### ISSUE TITLE
More information on cloud.node.auto_attributes setting

### ISSUE THREAD

**Issue by aedades** [elastic/elasticsearch-cloud-aws#256]
Hello - I wanted to do a sanity check on some settings regarding shard allocation awareness.  The docs for this setting state:

Though not dependent on actually using ec2 as discovery (but still requires the cloud aws plugin installed), the plugin can automatically add node attributes relating to ec2 (for example, availability zone, that can be used with the awareness allocation feature). In order to enable it, set cloud.node.auto_attributes to true in the settings.

Could you please provide more information on this setting and how it should be used?  Our current configuration running 1.5 uses the below settings for allocating shards based on AZ:
```
cloud.node.auto_attributes: true
routing.allocation.awareness.attributes: az
cloud.aws.region: us-west-2
node.az: us-west-2b
```
By setting cloud.node.auto_attributes: true, are the region and AZ settings necessary, or can they be omitted and still achieve the same effect?  Is this configuration valid for both 1.x and 2.x versions (I noticed the current docs use `routing.allocation.awareness.attributes: zone` instead)?

**Comment by dadoonet** [comment]
Did you get the answer you were looking for? If so, do you think it should be documented somewhere?
