### ISSUE TITLE
Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by drora** [elastic/elasticsearch-cloud-aws#258]
Hi,
is there a way to discover nodes behind amazon elasticsearch service? (currently v1.5)
the ec2 discovery feature obviously doesn't work in this case (even with a custom cloud.aws.ec2.endpoint setting).
essentially, the idea is to lunch a client node that will point to amazon elasticsearch services cluster entry-point along with IAM based auth.

**http://pokusak.blogspot.co.il/2015/10/aws-elasticsearch-request-signing.html

**Comment by dadoonet** [comment]
AFAIK AWS does not allow Java connections (transport layer) to its "elasticsearch as a service" service.
May be you can ask on discuss.elastic.co or on AWS forums?

Not directly related, in case you want to try it, [found](https://www.elastic.co/found) offers HTTP and transport access.

I'm closing this issue as I don't think we can solve anything in this plugin for your need. Feel free to reopen and comment if you think differently.
