### ISSUE TITLE
Does this plugin delete files from your S3 Bucket?

### ISSUE THREAD

**Issue by HenleyChiu** [elastic/elasticsearch-cloud-aws#259]
Does this plugin ever delete files from your S3 bucket when snapshotting or restoring? Or does it only insert and update files?

Reason I am asking is because I am considering implementing MFA (Multi-Factor Authentication) for Deletes in S3, which means all deletes must pass an authorization header.

**Comment by dadoonet** [comment]
It also deletes files when they are not needed anymore.

**Comment by HenleyChiu** [comment]
What if you're just restoring? Do you need delete privileges on the bucket files?

**Comment by dadoonet** [comment]
May be not needed if you use it with read only mode. IIRC it comes in elasticsearch 2.2... (May be 2.1).
