### ISSUE TITLE
Restart server if aws key changes in config?

### ISSUE THREAD

**Issue by HenleyChiu** [elastic/elasticsearch-cloud-aws#260]
Do I need to restart my Elastic server if I change the AWS key in my elasticsearch.yml config file?

**Comment by dadoonet** [comment]
AWS Client is created on a node level as soon it's needed and then is cached indefinitely.
It means that you need to restart the node.

Also, `elasticsearch.yml` file is read only once when the node starts. Even if the plugin was able to provide a smarter cache with expiration every x minutes for example, it would not be able to read the new settings.

@clintongormley WDYT? If doable, should we try to provide a hot reload mechanism for cloud clients (azure, aws and gce)?

**Comment by clintongormley** [comment]
@dadoonet No I don't.  Too much can go wrong

**Comment by dadoonet** [comment]
Thank you @clintongormley. 

Closing.
