### ISSUE TITLE
This plugin doesn't work with Elasticsearch 2.x

### ISSUE THREAD

**Issue by trekr5** [elastic/elasticsearch-cloud-aws#263]
Hi,

I'm upgrading ES from 1.7.3 to 2.1.1 and had plugins like elasticsearch-cloud-aws installed on my ES estate. However this plugin no longer works with ES 2.1.1. 

Do you have a version of this plugin that can work with ES 2.1.1 ?

Thanks

**Comment by dadoonet** [comment]
As stated in the README, read https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws.html
