### ISSUE TITLE
Changing AWS Credentials

### ISSUE THREAD

**Issue by k2xl** [elastic/elasticsearch-cloud-aws#264]
Question:
What's the recommended way to change the AWS credentials? Right now using env variables, but it looks like the plugin uses them on startup. Is there a way to POST new credentials, uninstall/reinstall the plugin in realtime? What's the best way?

**Comment by dadoonet** [comment]
You have to restart. Read this https://github.com/elastic/elasticsearch-cloud-aws/issues/260
