### ISSUE TITLE
Can't install plugin / No Checksum available

### ISSUE THREAD

**Issue by maubarrerag** [elastic/elasticsearch-cloud-aws#268]
Hello,

i executed this command to install the plugin:
`bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.7.1`

But i got this error:

Verifying https://download.elastic.co/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.7.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

I also try with another version number insted of 2.7.1 but i always get the same error. 

`bin/elasticsearch --version
Version: 2.2.0, Build: 8ff36d1/2016-01-27T13:32:39Z, JVM: 1.7.0_95
`

**Comment by dadoonet** [comment]
The README says

<img width="772" alt="universalaccessd universalaccessd aujourd hui at 18 30 15" src="https://cloud.githubusercontent.com/assets/274222/13435671/b30714ac-dfdb-11e5-8223-f0f5ee86f8b3.png">

`bin/plugin install cloud-aws` should be fine.
