### ISSUE TITLE
Allow Other methods of s3 server-side encryption

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/elasticsearch-cloud-aws#274]
Currently, by setting server_side_encryption to true, the only method that is allowed is aes256. It would be great if we could specify other s3 encryption methods, e.g. aws:kms.

For aws:kms, if the bucket has a default key, it's just a matter of including the correct header, so one possibility may be an additional parameter to specify the value of the `x-amz-server-side-encryption` header to get sent with requests. But the ability to specify an ams key to use would also be great.

**Comment by dadoonet** [comment]
Hey Tyler 

Could you open this feature request in Elasticsearch repo where this plugin moved now?
