### ISSUE TITLE
Can't create discovery cluster on region us-east2

### ISSUE THREAD

**Issue by sanvir10** [elastic/elasticsearch-cloud-aws#280]
In Amazon recently we can create instances on region us-east2, but when a set it in the config i get this error:

![captura de pantalla de 2016-11-29 17-03-52](https://cloud.githubusercontent.com/assets/12051806/20732816/09bc64fe-b656-11e6-9c65-a5e46e8c5947.png)

This region will be supported?, 

regards.

**Comment by dadoonet** [comment]
Yes `us-east2` is not supported for this version of the plugin. See https://github.com/elastic/elasticsearch-cloud-aws/tree/v2.7.1/#region

You can manually define `cloud.aws.ec2.endpoint` though to something like `ec2.us-east-2.amazonaws.com`. That should work I believe. See https://github.com/elastic/elasticsearch-cloud-aws/tree/v2.7.1/#using-other-ec2-endpoint

I opened https://github.com/elastic/elasticsearch/issues/21881 to add it in recent versions of elasticsearch. As it's not a blocker, it will probably be implemented from 5.2.0 I believe.

Closing but let me know if the workaround does not work for you.

**Comment by sanvir10** [comment]
I added this :
cloud.aws.ec2.endpoint: ec2.us-east-2.amazonaws.com 

the config look like this;

cloud.aws.access_key: [KEY]
cloud.aws.secret_key: [SECRET]
cluster.name: mycluster
node.name: elastic1

discovery.type: "ec2"
discovery.zen.ping.multicast.enabled: false
discovery.ec2.groups: "securityTest"
discovery.ec2.host_type: "private_ip"
discovery.ec2.ping_timeout: "30s"
discovery.ec2.tag.cluster: "cluster"
cloud.aws.ec2.endpoint: "ec2.us-east-2.amazonaws.com"


but this don't work, 

regards.

**Comment by dadoonet** [comment]
Can you paste the full log please?

**Comment by sanvir10** [comment]
Sorry this is working now, was a mistake in the config with the group-security name.

Thanks so much

**Comment by dadoonet** [comment]
Great!
