### ISSUE TITLE
No automatic endpoint could be derived from region [us-east-2]

### ISSUE THREAD

**Issue by RomanMauricio** [elastic/elasticsearch-cloud-aws#283]
The region in CMH (Ohio) does not appear to be recognized

**Comment by dadoonet** [comment]
Which version?

**Comment by RomanMauricio** [comment]
I tested it on 2.4.3 and 2.4.4

**Comment by RomanMauricio** [comment]
I got around the problem by specifying cloud.aws.ec2.endpoint: ec2.us-east-2.amazonaws.com

**Comment by dadoonet** [comment]
Exactly. Note that this has been added in 5.2: https://github.com/elastic/elasticsearch/pull/21961
Also note that the repo is now living at https://github.com/elastic/elasticsearch as explained in the README.
