### ISSUE TITLE
Issue in Snapshot taking

### ISSUE THREAD

**Issue by Balamurali10** [elastic/elasticsearch-cloud-aws#284]
Hi all,

while taking snapshot in s3 repo, getting below expections 

{"error":"RemoteTransportException[[nodename][inet[/ip:port]][cluster/snapshot/create]]; nested: SnapshotCreationException[[my_s3_repository:snapshot_1] failed to create snapshot]; nested: IOException[Failed to get [snapshot-snapshot_1]]; nested: AmazonS3Exception[AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: xxxxxxxxxxxxxxxxx)]; ","status":500}

can any one help us!!!

**Comment by dadoonet** [comment]
This repo is now closed. Please ask on discuss.elastic.co with all details like versions (jvm, elasticsearch)
