### ISSUE TITLE
repository_verification_exception on aws s3

### ISSUE THREAD

**Issue by chaitu0292** [elastic/elasticsearch-cloud-aws#285]
Hi There,
I am running ES 2.4.2 and used bin/plugin install cloud-aws to install aws plugin.
Ours is a cluster setup with 5-hot(data),3-master,3-client and 2-warm(data) nodes
So when I tried to register a S3 repository am getting below error.
Command Used:
curl -XPUT 'http://localhost:9200/_snapshot/s3_dev_backup' -d '{
    "type": "s3",
    "settings": {
        "access_key": "<********>",
        "secret_key": "<********>",
        "bucket": "<********>",
        "region": "us-west-2",
        "max_retries": 3
    }
}'

Exception:
{
  "error" : {
    "root_cause" : [ {
      "type" : "repository_verification_exception",
      "reason" : "[s3_dev_backup] [OnNS_ykLQVe4kEKSt5ksAg, 'RemoteTransportException[[DATA-ip-xx.xx.xx.xx.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];'], [llUObhw6RiGaiIDgzTntXw, 'RemoteTransportException[[DATA-ip-xx.xx.xx.xx.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];'], [-v4lyXp5RJW2BDRfFuV4FA, 'RemoteTransportException[[HOT-ip-xx.xx.xx.xx.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];']]"
    } ],
    "type" : "repository_verification_exception",
    "reason" : "[s3_dev_backup] [OnNS_ykLQVe4kEKSt5ksAg, 'RemoteTransportException[[DATA-ip-xx.xx.xx.xx.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];'], [llUObhw6RiGaiIDgzTntXw, 'RemoteTransportException[[DATA-ip-xx.xx.xx.xx0.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];'], [-v4lyXp5RJW2BDRfFuV4FA, 'RemoteTransportException[[HOT-ip-1xx.xx.xx.xx.localdomain][xx.xx.xx.xx:9300][internal:admin/repository/verify]]; nested: RepositoryMissingException[[s3_dev_backup] missing];']]"
  },
  "status" : 500
}

I have read set verify = false will remove this exception but what are its impacts if want to restore a snapshot on to a different cluster.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

BTW this repository is now deprecated as it applied only up to 1.7 series.
