### ISSUE TITLE
Document max_snapshot_bytes_per_sec and max_restore_bytes_per_sec as available settings for S3 repositories

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch-cloud-aws#287]
The [S3 Repository](https://www.elastic.co/guide/en/elasticsearch/plugins/5.4/repository-s3-repository.html) section of the docs doesn't list `max_snapshot_bytes_per_sec` or `max_restore_bytes_per_sec` as valid settings. The current [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-snapshots.html#_shared_file_system_repository) might suggest those settings are exclusive to `"type": "fs"` repositories.

**Comment by dadoonet** [comment]
Hey Robbie. This repo is now closed as per README: https://github.com/elastic/elasticsearch-cloud-aws

Could you reopen that in elasticsearch repo instead?

**Comment by n0othing** [comment]
whoops! :) https://github.com/elastic/elasticsearch/issues/25522
