### ISSUE TITLE
When can you support aws mumbai region

### ISSUE THREAD

**Issue by sukantasaha** [elastic/elasticsearch-cloud-aws#288]
Hi we have launched es cluster in aws mumbai (ap-south-1) region with es 1.4 version, but do not see elasticsearch-cloud-aws supports ap-south-1 region.

When can we expect this

**Comment by dadoonet** [comment]
This repository is not live anymore as stated in the README.
Note that in 6.0 `region` setting has been removed. You need to use now the `endpoint` setting instead. Which you can also do with previous versions of the plugin. That means that you have a workaround to support `ap-south-1`.

BTW 1.7 is not supported anymore. So 1.4 neither. It's really urgent that you upgrade!
