### ISSUE TITLE
Adding S3 bucket for snapshot 

### ISSUE THREAD

**Issue by mudgilgaurav** [elastic/elasticsearch-cloud-aws#291]
I am trying to add S3 bucket for taking snapshot of my elastic cluster. I am running Elasticsearch 2.3.3 and installed plugin cloud-aws. Following is syntax of my request

curl -X POST "http://XXX.XXX.XXX.XXX:9200/_snapshot/s3_repository" -d '{"type": "s3","settings":{"bucket":"bucketname","region":"ap-south-1","access_key":"accesskey","secret_key":"secretkey","endpoint":"s3.ap-south-1.amazonaws.com","compress":true}}'

it gives me following error

{"error":{"root_cause":[{"type":"repository_exception","reason":"[s3_repository] failed to create repository"}],"type":"repository_exception","reason":"[s3_repository] failed to create repository","caused_by":{"type":"creation_exception","reason":"Guice creation errors:\n\n1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to execute HTTP request: bucketname.s3.ap-south-1.amazonaws.com\n  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.s3.S3Repository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error","caused_by":{"type":"amazon_client_exception","reason":"Unable to execute HTTP request: bucketname.s3.ap-south-1.amazonaws.com","caused_by":{"type":"unknown_host_exception","reason":"bucketname.s3.ap-south-1.amazonaws.com"}}}},"status":500}

**Comment by dadoonet** [comment]
This repository is now closed.

Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by mudgilgaurav** [comment]
@dadoonet thanks for quick response. Added my question on discuss.elastic.co.
