### ISSUE TITLE
[s3_repository] path is not accessible on master node

### ISSUE THREAD

**Issue by arispeng** [elastic/elasticsearch-cloud-aws#292]
My elasticsearch 2.4.6 cluster (hosted on amazon east data center) is having issues with the aws-cloud 2.4.6 plugin, I have configured my elasticsearch.yml file as instructed by configuration . 
cloud:
  aws:
    access_key: XXX
    secret_key: XXX
The S3 bucket is set up to have s3Full access. 
I did a testing before my elasticsearch cluster upgrade, which was 1.7.6 version using aws-cloud plugin from this documentation -https://github.com/elastic/elasticsearch-cloud-aws. The snapshot and restore process was working perfectly fine until recently I upgraded my ES version to 2.4.6.

Here's the curl script I usually use to create s3_repository.  PS, I can manually upload files to the s3 bucket using aws cli.  
{ ~ }  » curl -XPUT 'http://localhost:10557/_snapshot/s3_repository?pretty' -H 'Content-Type: application/json' -d'                       ~
\ {
\   "type": "s3",
\   "settings": {
\     "bucket": "my-bucket",
\     "region": "us-east",
\      "access_key": "XXX",
\      "secret_key": "XXX"
\   }
\ }
\ '
{
  "error" : {
    "root_cause" : [ {
      "type" : "amazon_s3_exception",
      "reason" : "amazon_s3_exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 3906E3E1E996060C)"
    } ],
    "type" : "repository_verification_exception",
    "reason" : "[s3_repository] path  is not accessible on master node",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "i_o_exception: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 3906E3E1E996060C), S3 Extended Request ID: Q/OWbf2aljoROoeLB48dfZ8YqBKzKw5JaQvpxrHwXXd4WT4qUp5nlHs8fCWKV19dIrCPXtW6Clo=",
      "caused_by" : {
        "type" : "amazon_s3_exception",
        "reason" : "amazon_s3_exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 3906E3E1E996060C)"
      }
    }
  },
  "status" : 500
}

Is anyone else having similar issues ? Have cloud-aws plugin being regression tested recently specifically on 2.4.X version ?  I did see some similar issues but people are reporting something wrong with s3 access_key/secret_key, which in my case is not the issue.

**Comment by dadoonet** [comment]
As per README this repository is now closed.
Please ask on discuss.elastic.co.
