### ISSUE TITLE
SnapshotMissingException

### ISSUE THREAD

**Issue by chaitu0292** [elastic/elasticsearch-cloud-aws#293]
SnapshotMissingException[[s3full:201608151615] is missing]; nested: FileNotFoundException[Blob object [snapshot-201608151615] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 1B6FB23C4BC5940D)];

Elasticsearch Version: 5.5.0

**Comment by dadoonet** [comment]
This repository is now closed. Please ask on discuss.elastic.co

**Comment by chaitu0292** [comment]
Am sorry I did not understand what do you ment by 'repository is now closed'. @dadoonet

**Comment by dadoonet** [comment]
Read the first lines of the README.
