### ISSUE TITLE
Getting InvalidLocationConstraint while creating the bucket in US_EAST_1 region

### ISSUE THREAD

**Issue by vagdevipedalenka** [elastic/elasticsearch-cloud-aws#296]
Please help me to solve this issue,

I am getting following error while creating the bucket.
 Code: Create bucket in US_EAST_1 region
            AmazonS3Client m_s3Client;
            CreateBucketRequest obj = new CreateBucketRequest("example_bucket");
           Bucket bucket = m_s3Client.createBucket(obj); 

Note:  I am not passing the region name while creating the bucket:

Error:
CreateBucket - com.amazonaws.services.s3.model.AmazonS3Exception: The specified location constraint is not valid. For more information about Regions, see How to Select a Region for Your Buckets. (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 1647771648), S3 Extended Request ID: null

**Comment by dadoonet** [comment]
Not related to elasticsearch.
