### ISSUE TITLE
Enable whitelisting of a email domain opposed to having to do so for each email address

### ISSUE THREAD

**Issue by tsully193** [elastic/elasticsearch-cloud-aws#298]
Currently for any Elastic Cloud customer that wants to get email alerts via watchers they have to be added one by one manually. This can be a largely tedious process for an entire company. A way to be able to whitelist a specific domain via something like "*@blah.com" would be very useful

**Comment by dadoonet** [comment]
This used to be a repository for an elasticsearch plugin which was doing discovery on EC2.
Not related to cloud.elastic.co in any way.

Could you contact the cloud support team instead?

**Comment by tsully193** [comment]
Hey @dadoonet support actually directed me to open a feature issue. Support ticket #00348407. I also specifically asked which repo because none of them seemed appropriate, and they said this one.

**Comment by dadoonet** [comment]
Ok. Let me chat with the support team.

**Comment by 3uzbcqje** [comment]
So, what was the solution? I have the same problem?

**Comment by 3uzbcqje** [comment]
Nevermind, I have the problem in elastic.co, not on AWS...
