### ISSUE TITLE
Version of AWS SDK should be updated

### ISSUE THREAD

**Issue by hyper750** [elastic/elasticsearch-cloud-aws#301]
According to https://aws.amazon.com/blogs/developer/tls-1-3-incompatibility-with-aws-sdk-for-java-versions-1-9-5-to-1-10-31/ AWS SDK should be updated to 1.12.x or 2.x. Right now the plugin is using AWS SDK 1.10.12 version https://github.com/elastic/elasticsearch-cloud-aws/blob/v2.7.1/pom.xml#L35

**Comment by dadoonet** [comment]
Hey! As stated in the [README](https://github.com/elastic/elasticsearch-cloud-aws), this project has moved.
It was up to version 1.x which is not maintained anymore.

But thanks for the effort of providing a fix.

**Comment by hyper750** [comment]
Hi, thanks for the response but I need the solution anyways, since I'm using elasticsearch 1.7.
