### ISSUE TITLE
Logstash 1.4 + cloud-aws 2.1.0 + elasticsearch 1.1

### ISSUE THREAD

**Issue by ghost974** [elastic/elasticsearch-cloud-aws#71]
I used to copy elasticsearch.yml in /usr/local/bin/logstash along with cloud-aws directory and it was working fine with logstash 1.3

Now with 1.4, I copied cloud-aws in /opt/logstash/vendor/ and I checked in the logs that it's properly loaded, but the yml file is not. I tried to put it a bit everywhere but no luck.

Is this plugin supported with the last version of logstash ?

**Comment by pedalair** [comment]
I am trying to implement this using LS1.4.2. I have got the jars in the ES/lib dir, added an elasticsearch.yml file to the /opt/logstash dir.  I added LS_JAVA_OPTS="-Djava.io.tmpdir=${LS_HOME} -Des.config=/opt/logstash/elasticsearch.yml " to the ini file.  
In my Logstash config i am just specifying the Clustername, protocol and index.  I have tried with both transport and node protocol yet i still cannot get the discovery to work.  If i specify a host explicitly it connects straight away so there is a path to ES.
I would appreciate some more explicit pointers - ie things that should/shouldn't go into the elasticsearch.yml, logstash.conf etc.  Thanks

**Comment by ghost974** [comment]
@pedalair , can you confirm you have elasticsearch-cloud-aws-2.1.1.jar in /opt/logstash/vendor/jar/elasticsearch-1.1.1/lib/ ?
/opt/logstash/elasticsearch.yml should be the exact same file used in ES.
The LS_JAVA_OPTS was added in your logstash indexer init (if you split indexer and shipper).
In logstash indexer config, I have:
```
    output {
      elasticsearch {
            cluster => "myESCluster"
      }
    }
```
I suggest you enable debug and look at the logs, you'll see what the cloud-aws plugin spit out.

**Comment by pedalair** [comment]
Thanks for the advice - had the setup as described - i ended up spinning up an ES Client in the same Security Group and discovering that i needed to update my security group port to allow inbound as well as outbound traffic from 9300 as I had Logstash in a seperate SG to my main cluster.
